language: python
sudo: false
matrix:
  include:
    - os: linux
      dist: xenial
      python: "3.7"
    - os: osx
      language: generic
services:
  - docker
git:
  depth: 1
install:
  - pip install -Ur requirements.txt
  - python setup.py develop
  - rm -rf build
script:
  - cd $TRAVIS_BUILD_DIR
  - python main.py -t gerrit,jenkins,jira
  - coverage run --source=mailtrigger,tests -m py.test -v --capture=no tests/logger tests/trigger tests/*.py
after_success:
  coveralls
