language: python
sudo: false
matrix:
  include:
    - os: linux
      dist: xenial
      python: "3.7"
services:
  - docker
git:
  depth: 1
install:
  - pip install -Ur requirements.txt
  - python setup.py develop
  - rm -rf build
script:
  - cd $TRAVIS_BUILD_DIR
  - coverage run --source=mailtrigger -m py.test -v --capture=no tests/logger tests/mailer tests/scheduler tests/trigger tests/*.py
after_success:
  coveralls
